logging:
  level:
    com:
      prakash:
        popular:
          github:
            repos:
              populargithubrepos: DEBUG
resilience4j:
  circuitbreaker:
    instances:
      gitHubDataProviderService:
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
spring:
  cache:
    cache-names:
      - repositoryCache
    caffeine:
      spec: maximumSize=100, expireAfterAccess=30s